title: Slides for talks - BÃ©rÃ©nice Batut
email: berenice.batut@gmail.com
description: >
  This repository served the slides for my talks
repository: "bebatut-slides/bebatut-slides.github.io"
twitter: bebatut
linkedin: berenicebatut
gitter: bebatut
orcid: 0000-0001-9852-1987
